api.v1.token.secret=${token_secret}
api.v1.token.issuer=${token_issuer}
api.v1.token.expiration-seconds=${token_expiration_seconds}

spring.datasource.url=jdbc:postgresql://${db_host}:${db_port}/${db_name}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

server.forward-headers-strategy=framework
spring.web.error.include-stacktrace=never

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
