api.v1.token.secret=${token_secret}
api.v1.token.issuer=${token_issuer}
api.v1.token.expiration-seconds=${token_expiration_seconds}

api.v1.cors.url=${cors_url}
api.v1.cors.methods=${cors_methods}
api.v1.cors.headers=${cors_headers}

spring.datasource.url=jdbc:postgresql://${db_host}:${db_port}/${db_name}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

api.v1.refresh-token.expires-in=7

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

server.forward-headers-strategy=framework
spring.web.error.include-stacktrace=never

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

management.endpoint.health.show-details=when_authorized
management.endpoint.health.roles=ADMIN
